import 'package:flutter/material.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedDokterSpesialisBedahUmumWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedDrJiaeruuSpAWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratediconhomeWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedHelloAlamsyahWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratediconbellWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedDrKurehaDSpBWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedDoc1Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedDoc2Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedIc_starWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedDokterSpesialisAnakWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedStayHealtywithourspecialistWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratediconenvelopeclosedWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax2widget/generated/GeneratediconcreditcardWidget.dart';

/* Frame iPhone 14 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 92, 84, 115),
                              ),
                            ),
                            Positioned(
                              left: 67.0,
                              top: 534.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 266.0,
                              child: GeneratedDoc2Widget(),
                            ),
                            Positioned(
                              left: 66.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 266.0,
                              child: GeneratedDoc1Widget(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 15.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 58.0,
                              child: GeneratedIc_starWidget(),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 71.82022094726562,
                              height: 70.5,
                              child: GeneratedGroup8Widget(),
                            ),
                            Positioned(
                              left: 88.0,
                              top: 11.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 51.0,
                              child: GeneratedHelloAlamsyahWidget(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 46.0,
                              child:
                                  GeneratedStayHealtywithourspecialistWidget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 473.0,
                              right: null,
                              bottom: null,
                              width: 313.0,
                              height: 35.0,
                              child: GeneratedDrKurehaDSpBWidget(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 313.0,
                              height: 35.0,
                              child: GeneratedDrJiaeruuSpAWidget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 500.0,
                              right: null,
                              bottom: null,
                              width: 359.0,
                              height: 51.0,
                              child: GeneratedDokterSpesialisBedahUmumWidget(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 837.0,
                              right: null,
                              bottom: null,
                              width: 359.0,
                              height: 51.0,
                              child: GeneratedDokterSpesialisAnakWidget(),
                            ),
                            Positioned(
                              left: 316.0,
                              top: 482.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 24.0,
                              child: GeneratedGroup5Widget(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 818.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 24.0,
                              child: GeneratedGroup6Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.12093023255813953;

                                final double height = constraints.maxHeight *
                                    0.048819746582293204;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3744186046511628,
                                      y: constraints.maxHeight *
                                          0.9334763948497854,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconhomeWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.10697674418604651;

                                final double height =
                                    constraints.maxHeight * 0.04440431635778861;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.7883720930232558,
                                      y: constraints.maxHeight *
                                          0.9377682403433476,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratediconenvelopeclosedWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 135.0,
                              right: null,
                              bottom: null,
                              width: 338.0,
                              height: 38.0,
                              child: GeneratedGroup7Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.1186046511627907;

                                final double height = constraints.maxHeight *
                                    0.036611139518508584;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.1697674418604651,
                                      y: constraints.maxHeight *
                                          0.9420600858369099,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconcreditcardWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.11743123254110646;

                                final double height =
                                    constraints.maxHeight * 0.05417964591488818;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5837209302325581,
                                      y: constraints.maxHeight *
                                          0.9334763948497854,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconbellWidget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
