import 'package:flutter/material.dart';

/* Rectangle calendar 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCalendar2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 42.0,
      height: 42.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/877666b63e2c5e9a19aaa2fe43934c79816c1be8.png",
          color: null,
          fit: BoxFit.cover,
          width: 42.0,
          height: 42.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
