import 'package:flutter/material.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratedFrameWidget2.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratediconcreditcardWidget1.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratedFrameWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratedHallodeckalwaysreadyandcareforyouandyourfamilyWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratedPngtransparentphysiciancancercartoondoctorcartooncharac.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratediconenvelopeclosedWidget1.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratedFrameWidget1.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratedFrameWidget3.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratediconhomeWidget1.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax3widget/generated/GeneratediconbellWidget1.dart';

/* Frame iPhone 14 Pro Max - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 93, 84, 116),
                              ),
                            ),
                            Positioned(
                              left: -59.0,
                              top: 198.0,
                              right: null,
                              bottom: null,
                              width: 548.0,
                              height: 455.0,
                              child:
                                  GeneratedPngtransparentphysiciancancercartoondoctorcartooncharac(),
                            ),
                            Positioned(
                              left: 108.0,
                              top: 653.0,
                              right: null,
                              bottom: null,
                              width: 72.0,
                              height: 72.0,
                              child: GeneratedFrameWidget(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 657.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 78.0,
                              child: GeneratedFrameWidget1(),
                            ),
                            Positioned(
                              left: 108.0,
                              top: 734.0,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 57.0,
                              child: GeneratedFrameWidget2(),
                            ),
                            Positioned(
                              left: 275.0,
                              top: 661.0,
                              right: null,
                              bottom: null,
                              width: 61.0,
                              height: 61.0,
                              child: GeneratedFrameWidget3(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 98.0,
                              right: null,
                              bottom: null,
                              width: 363.0,
                              height: 93.0,
                              child:
                                  GeneratedHallodeckalwaysreadyandcareforyouandyourfamilyWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.1186046511627907;

                                final double height = constraints.maxHeight *
                                    0.036611139518508584;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.15348837209302327,
                                      y: constraints.maxHeight *
                                          0.9420600858369099,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconcreditcardWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.12093023255813953;

                                final double height = constraints.maxHeight *
                                    0.048819746582293204;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.36511627906976746,
                                      y: constraints.maxHeight *
                                          0.9356223175965666,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconhomeWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.11743123254110646;

                                final double height =
                                    constraints.maxHeight * 0.05417964591488818;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5651162790697675,
                                      y: constraints.maxHeight *
                                          0.9356223175965666,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconbellWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.10697674418604651;

                                final double height =
                                    constraints.maxHeight * 0.04440431635778861;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.7604651162790698,
                                      y: constraints.maxHeight *
                                          0.9377682403433476,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratediconenvelopeclosedWidget1(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
