import 'package:flutter/material.dart';

/* Rectangle calendar 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCalendar1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 42.0,
      height: 42.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/6abae4b7d405f34b59976a1e0905ec6f123474a1.png",
          color: null,
          fit: BoxFit.cover,
          width: 42.0,
          height: 42.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
