import 'package:flutter/material.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedFINDYOURSCHEDULEWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratediconbellWidget2.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratediconenvelopeclosedWidget2.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedCHOOSEYOURPAYMENTWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedPaymentWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedApplepayWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratediconhomeWidget2.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedCoin1Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedCreditcardWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax4widget/generated/GeneratediconcreditcardWidget2.dart';

/* Frame iPhone 14 Pro Max - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 975.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 93, 84, 116),
                              ),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 448.0,
                              height: 736.0,
                              child: GeneratedRectangle3Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: 54.0,
                              right: null,
                              bottom: null,
                              width: 391.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: -1.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedCHOOSEYOURPAYMENTWidget()),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 55.0,
                              child: GeneratedCreditcardWidget(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 115.0,
                              child: GeneratedApplepayWidget(),
                            ),
                            Positioned(
                              left: 298.0,
                              top: 115.0,
                              right: null,
                              bottom: null,
                              width: 65.0,
                              height: 65.0,
                              child: GeneratedPaymentWidget(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 275.0,
                              right: null,
                              bottom: null,
                              width: 389.0,
                              height: 83.0,
                              child: GeneratedImage1Widget(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 399.0,
                              right: null,
                              bottom: null,
                              width: 258.0,
                              height: 38.0,
                              child: GeneratedFINDYOURSCHEDULEWidget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 669.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 43.0,
                              child: GeneratedCoin1Widget(),
                            ),
                            Positioned(
                              left: 75.0,
                              top: 528.0,
                              right: null,
                              bottom: null,
                              width: 267.0,
                              height: 39.0,
                              child: GeneratedRectangle4Widget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 600.0,
                              right: null,
                              bottom: null,
                              width: 267.0,
                              height: 39.0,
                              child: GeneratedRectangle5Widget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 672.0,
                              right: null,
                              bottom: null,
                              width: 267.0,
                              height: 39.0,
                              child: GeneratedRectangle6Widget(),
                            ),
                            Positioned(
                              left: 106.0,
                              top: 792.0,
                              right: null,
                              bottom: null,
                              width: 217.0,
                              height: 50.0,
                              child: GeneratedRectangle7Widget1(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 785.0,
                              right: null,
                              bottom: null,
                              width: 190.0,
                              height: 47.0,
                              child: GeneratedGroup9Widget(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 785.0,
                              right: null,
                              bottom: null,
                              width: 190.0,
                              height: 47.0,
                              child: GeneratedGroup10Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.1186046511627907;

                                final double height = constraints.maxHeight *
                                    0.036611139518508584;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.12325581395348838,
                                      y: constraints.maxHeight *
                                          0.9388412017167382,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconcreditcardWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.12093023255813953;

                                final double height = constraints.maxHeight *
                                    0.048819746582293204;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.36046511627906974,
                                      y: constraints.maxHeight *
                                          0.9345493562231759,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconhomeWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.11743123254110646;

                                final double height =
                                    constraints.maxHeight * 0.05417964591488818;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5837209302325581,
                                      y: constraints.maxHeight *
                                          0.9345493562231759,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconbellWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.10697674418604651;

                                final double height =
                                    constraints.maxHeight * 0.04440431635778861;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.7953488372093023,
                                      y: constraints.maxHeight *
                                          0.9388412017167382,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratediconenvelopeclosedWidget2(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
