import 'package:flutter/material.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax1widget/generated/GeneratedHallodeckWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax1widget/generated/GeneratedTreatPatientsLikeAQueenWidget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax1widget/generated/GeneratedExploreandfeeltheprofessionalexperiencewithourspecialis.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax1widget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/hallodeckapp/generatediphone14promax1widget/generated/GeneratedGetstartedWidget.dart';

/* Frame iPhone 14 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 188, 191, 250),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -75.0,
                              right: null,
                              bottom: null,
                              width: 516.0,
                              height: 1007.0,
                              child: GeneratedGetstartedWidget(),
                            ),
                            Positioned(
                              left: -23.0,
                              top: -16.0,
                              right: null,
                              bottom: null,
                              width: 472.0,
                              height: 339.0,
                              child: GeneratedRectangle1Widget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 54.0,
                              right: null,
                              bottom: null,
                              width: 420.0,
                              height: 51.0,
                              child: GeneratedTreatPatientsLikeAQueenWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 92.0,
                              right: null,
                              bottom: null,
                              width: 408.0,
                              height: 52.0,
                              child:
                                  GeneratedExploreandfeeltheprofessionalexperiencewithourspecialis(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 22.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 37.0,
                              child: GeneratedHallodeckWidget(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 230.0,
                              height: 56.0,
                              child: GeneratedGroup12Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
